setup.py: fix pygments bug
Up the version of pygments by upgrading mkdocs_material, mkdocs and
pymdown-extensions by dependency, to solve this error:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pygments/__init__.py", line 61, in format
    formatter.format(tokens, realoutfile)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pygments/formatter.py", line 94, in format
    return self.format_unencoded(tokensource, outfile)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pygments/formatters/html.py", line 981, in format_unencoded
    source = self.wrap(source)
TypeError: wrap() missing 1 required positional argument: 'outfile'

Signed-off-by: Gilles DOFFE <g.doffe@gmail.com>